name: CI iwvg devops
on:
  push:
    branches: [ develop, release, staging, master, v-* ]

jobs:
  devops:
    name: Tests & CodeQL & SonarCloud
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: read
      security-events: write

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: 🛡️ Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          queries: security-extended

      - name: ✅ Run Unit & Integration Test & Functional Test
        run: mvn -B verify

      # -------------------------------------------------------------
      # PASO: Notificación de Éxito en Slack
      # -------------------------------------------------------------
      - name: Notificar éxito a Slack
        if: success() # Solo se dispara si la compilación y tests fueron exitosos
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {
              "text": "✅ *¡Integración Continua Exitosa!*\n*Repositorio:* ${{ github.repository }}\n*Rama:* ${{ github.ref_name }}\n*Autor:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}\n*Estado:* La API de Spring Boot ha sido compilada y validada correctamente con las pruebas de Maven."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # -------------------------------------------------------------
      # PASO: Notificación de Fallo en Slack
      # -------------------------------------------------------------
      - name: Notificar fallo a Slack
        if: failure() # Solo se dispara si falló algún paso anterior
        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
        with:
          payload: |
            {
              "text": "🚨 *¡Fallo en la Integración Continua!*\n*Repositorio:* ${{ github.repository }}\n*Rama:* ${{ github.ref_name }}\n*Autor:* ${{ github.actor }}\n*Commit:* ${{ github.sha }}\n*Estado:* La compilación o las pruebas han fallado. Revisen los logs en GitHub Actions."
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: 🔍 CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:java"

      # Organización de la cuenta de Sonar: cesarasdf
      - name: 🏷️ Extract artifact from pom & Sonar Organization
        run: |
          echo "ORGANIZATION=cesarasdf" >> $GITHUB_ENV
          echo "ARTIFACT=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)" >> $GITHUB_ENV

      - name: 📊 Sonar Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: >
          mvn -B sonar:sonar
          -Dsonar.projectKey=cesarasdf_${{ env.ARTIFACT }}
          -Dsonar.organization=cesarasdf
          -Dsonar.host.url=https://sonarcloud.io 
          -Dsonar.token=$SONAR_TOKEN
